spring:
  application:
    name: vehicles-api
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:vehicledatasource

server:
  port: 8080

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      default: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

logging:
  level:
    com.udacity.vehicles-api: DEBUG

